# Generated by Django 5.0.7 on 2024-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_orders', '0002_order_email_order_marketing_consent_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
